### ISSUE TITLE
Error while compiling Nginx with Mapcache support

### ISSUE THREAD

**Issue by ThomasG77** [MapServer/mapcache#312]
The recipe I've used

Mapcache (I don't mentioned the deps here)

```
cd /usr/local/src
wget https://github.com/MapServer/mapcache/archive/refs/heads/branch-1-14.zip
unzip branch-1-14.zip
mv mapcache-branch-1-14/ mapcache
cd mapcache
mkdir build
cd build
cmake ..
make
sudo make install
cd ..
```

Nginx compilation

```
mkdir nginx
cd nginx
wget https://nginx.org/download/nginx-1.23.4.tar.gz
unp nginx-1.23.4.tar.gz
cd nginx-1.23.4
./configure --add-module=/usr/local/src/mapcache/build/nginx
make
```

While doing `make`, I got this issue

```
make -f objs/Makefile
make[1] : on entre dans le répertoire « /usr/local/src/nginx/nginx-1.20.2 »
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g    -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/mapcache/build/include -I /usr/include/apr-1.0 -I objs -I src/http -I src/http/modules \
	-o objs/addon/nginx/ngx_http_mapcache_module.o \
	/usr/local/src/mapcache/nginx/ngx_http_mapcache_module.c
/usr/local/src/mapcache/nginx/ngx_http_mapcache_module.c: In function ‘ngx_http_mapcache’:
/usr/local/src/mapcache/nginx/ngx_http_mapcache_module.c:303:36: error: ‘mapcache_context’ {aka ‘struct mapcache_context’} has no member named ‘mapcache_cfg’
   mapcache_cache_child_init(ctx,ctx->mapcache_cfg,ctx->pool);
                                    ^~
make[1]: *** [objs/Makefile:1207: objs/addon/nginx/ngx_http_mapcache_module.o] Error 1
make[1] : on quitte le répertoire « /usr/local/src/nginx/nginx-1.20.2 »
make: *** [Makefile:10: build] Error 2
```

I had to replace in `/usr/local/src/mapcache/nginx/ngx_http_mapcache_module.c` line

```
mapcache_cache_child_init(ctx,ctx->cfg,ctx->pool);
```

by

```
mapcache_cache_child_init(ctx,ctx->config,ctx->pool);
```

to compile as `cfg` is not part of the struct `mapcache_context` but `config` is https://github.com/MapServer/mapcache/blob/main/include/mapcache.h#L221
Not sure my guess was right. If yes, fix need to be done at https://github.com/MapServer/mapcache/blob/main/nginx/ngx_http_mapcache_module.c#L303 level

**Comment by jmckenna** [comment]
@ThomasG77 can you open a Pull Request for this change?  (maybe it could be included in the 1.14.1 release)

**Comment by adrianrieck** [comment]
@ThomasG77 

This problem wasn't in version 1.12.0 as I get my builds to work fine in the 1.12.0 version.

After your https://github.com/MapServer/mapcache/blob/main/nginx/ngx_http_mapcache_module.c#L303 change, did you test running nginx successfully? 

Thanks to your change I can get it to compile in 1.14.0, but actually running nginx produces errors like this:

`/usr/local/openresty/bin/openresty: symbol lookup error: /usr/local/openresty/bin/openresty: undefined symbol: mapcache_cache_child_init`

Any help would be appreciated, Thanks!

**Comment by adrianrieck** [comment]
@jmckenna 

It looks like I can get `1.14` to compile and run and serve cache requests if I remove these lines:

https://github.com/MapServer/mapcache/blob/0b85061c673ade7a0890759105c7db79a21af87d/nginx/ngx_http_mapcache_module.c#L303-L307

@marisn added these lines in https://github.com/MapServer/mapcache/commit/ac2ac10e961b774f31a1559039ada23b4e40dc58 perhaps @marisn could comment if there is a less destructive solution.

I don't mind doing a pull request if deleting is a good option so that it makes it to `1.14.1`

Thanks!

**Comment by tbonfort** [comment]
@adrianrieck deleting that block is not a solution as it calls required initializers for some storage backends (i.e. the reason for @marisn 's PR). The "correct" solution is to understand and fix why that call is failing under nginx.

**Comment by tbonfort** [comment]
@adrianrieck, after looking through the PR's code, the fact that you are getting that error at runtime and not at compile time makes me believe that your nginx at runtime is linking against an older (i.e. incorrect, probably 1.12) version of libmapcache.so

**Comment by adrianrieck** [comment]
@tbonfort 


> that your nginx at runtime is linking against an older (i.e. incorrect, probably 1.12) version of libmapcache.so

Yes, thank you that was my problem. I had two `libmapcache.so` versions and it wouldn't see the new one until I ran `ldconfig`.

So to clarify now I have it working with just the `mapcache_cache_child_init(ctx,ctx->config,ctx->pool);` change on line https://github.com/MapServer/mapcache/blob/main/nginx/ngx_http_mapcache_module.c#L303

**Comment by marisn** [comment]
The code has been fixed. IMHO this can be closed now.
