### ISSUE TITLE
Fails to build mapserver source with MapServer 7.0.0

### ISSUE THREAD

**Issue by sebastic** [mapserver/mapcache#126]
The experimental mapserver source in MapCache 1.4 fails to build with MapServer 7.0.0 with the following error:
`error: 'mapcache_context' has no member named 'process_pool'`

It looks like this source hasn't been adapted to the new pooling yet. I'll disable this experimental feature in Debian package for now.

Context from the build log:
```
[ 87%] Building C object CMakeFiles/mapcache.dir/lib/source_mapserver.c.o
/usr/bin/cc  -Dmapcache_EXPORTS -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIE -pie -Wl,-z,relro -Wl,-z,now -D_FORTIFY_SOURCE=2  -Wall -fPIC -I/usr/include/apr-1.0 -I/usr/include/pixman-1 -I/usr/include/x86_64-linux-gnu -I/usr/share/mapserver/cmake/../../../include -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/cairo -I/usr/include/postgresql -I/usr/include/gdal -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/mapserver -I/tmp/buildd/mapcache-1.4.0/include -I/tmp/buildd/mapcache-1.4.0/obj-x86_64-linux-gnu/include      -DLINUX -D_REENTRANT -D_GNU_SOURCE -o CMakeFiles/mapcache.dir/lib/source_mapserver.c.o   -c /tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c
/usr/bin/cmake -E cmake_progress_report /tmp/buildd/mapcache-1.4.0/obj-x86_64-linux-gnu/CMakeFiles 44
/tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c: In function '_get_mapboj':
/tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c:89:43: error: 'mapcache_context' has no member named 'process_pool'
       mapobj_container = apr_hash_make(ctx->process_pool);
                                           ^
/tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c:101:39: error: 'mapcache_context' has no member named 'process_pool'
                               src, ctx->process_pool);
                                       ^
/tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c: In function '_mapcache_source_mapserver_render_map':
/tmp/buildd/mapcache-1.4.0/lib/source_mapserver.c:196:5: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
     image->format->vtable->getRasterBufferHandle(image,&rb);
     ^
CMakeFiles/mapcache.dir/build.make:1023: recipe for target 'CMakeFiles/mapcache.dir/lib/source_mapserver.c.o' failed
```

**Comment by tbonfort** [comment]
Bas,
Correct, I haven't updated it and won't be able to do so myself as I'll be
off for holidays until september. Anyways, given it's marked as
experimental and that it does have stability issues, I'm not certain it's a
good idea to include it in the debian releases.
cheers,

**Comment by markathomas** [comment]
Hi, I'm getting this same compile problem against MapServer 6.2.2.  Is there no workaround for this error or no plan to fix this?

**Comment by tbonfort** [comment]
no plans to revive it myself, but will accept PRs

**Comment by markathomas** [comment]
If I understand it correctly this bug prevents building MapCache against MapServer 7.0.0 and now MapServer 6.2.2 but there are no plans to fix it?  How are users suppose to use this version of MapCache then?

**Comment by tbonfort** [comment]
native mapserver as a backend has never been supported. the first class backend is WMS through http

**Comment by markathomas** [comment]
ok, thank you
